version: '2'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27020:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
  bimiot:
    image: 'bimiot'
    build:
      context: .
    container_name: bimiot
    ports:
      - "80:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./Projects:/Projects

volumes:
  data: {}