version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27020:27017"
    volumes:
      - data:/data
  bimiot:
    image: 'bimiot/bimiot:1.1.0'
    depends_on:
      - mongodb
    container_name: bimiot
    ports:
      - "80:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  data: {}

networks:
  default:
    name: mongodb_network
