version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27020:27017"
    volumes:
      - data:/data
  bimiot:
    image: 'bimiot'
    depends_on:
      - mongodb
    build:
      context: .
    container_name: bimiot
    ports:
      - "80:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  data: {}

networks:
  default:
    name: mongodb_network