version: '2'

services:
  bimiot:
    image: 'bimiot'
    build:
      context: .
    container_name: bimiot
    ports:
      - "80:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./Projects:/Projects
